### ISSUE TITLE
Weapon's "complexity" field is mandatory, but some weapons don't have a complexity

### ISSUE THREAD

**Issue by plu2k** [elyukai/optolith-database-schema#16]
Current examples (pickbreaker branch):
- Data\Equipment\Weapons\67_Stone.yml
- Data\Equipment\Weapons\86_Soap-In-Cloth-Tube.yml

**Comment by elyukai** [comment]
Damn. 🙃 I‘ll fix that, thanks!

**Comment by elyukai** [comment]
Fixed in 13a3b53.

**Comment by plu2k** [comment]
After some reconsideration I think came to the conlcusion that the cleaner solution was to move the particluar items to another category - I suggest to roll back.
