### ISSUE TITLE
Weapon/restricted_to_traditions[] restricted to MagicalTraditionReference

### ISSUE THREAD

**Issue by plu2k** [elyukai/optolith-database-schema#19]
https://github.com/elyukai/optolith-database-schema/blob/main/docs/reference/equipment/item/Weapon.md#Weapon/restricted_to_traditions[]

This property should probably support blessed_traditions, too?
Example: Data\Equipment\Weapons\19_Ravens-Beak.yml - currently causes errors.

**Comment by elyukai** [comment]
If a weapon is blessed, there is a separate property `sanctified_by`, which should handle that.
